on:
  push:
    branches:
      - master
      - develop
      - 'feature/*'
    paths-ignore:
      - '**.md'
      - 'THANKS'
      - 'LICENSE'
jobs:
  test:
    name: Android Test on node 11.x and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: 11.x
      - name: yarn install
        run: |
          yarn install
        working-directory: ./test/Touchstone
      - name: rm -rf node_modules/react-native-webrtc-kit
        run: |
          rm -rf node_modules/react-native-webrtc-kit
        working-directory: ./test/Touchstone
      - name: git clone ../../../react-native-webrtc-kit node_modules/react-native-webrtc-kit
        run: |
          git clone ../../../react-native-webrtc-kit node_modules/react-native-webrtc-kit
        working-directory: ./test/Touchstone
      - name: react-native link
        run: |
          $(npm bin)/react-native link --platforms android
        working-directory: ./test/Touchstone
      - name: gradlew check
        run: |
          cd android/
          ./gradlew check
        working-directory: ./test/Touchstone
